# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 洛易
subtitle: 一个软件工程师
description:
author: debugtalk
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your website is in a subdirectory (such as http://example.org/blog), set url to http://example.org/blog and set root to /blog/.
url: https://threew.github.io
root: /
permalink: :title/
permalink_defaults:
  lang: en

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false          # Transform title into titlecase
external_link: true       # Open external links in new tab
filename_case: 0          # Transform filenames to 1 lower case; 2 upper case
render_drafts: false      # Display drafts?
post_asset_folder: false  # separate assets on a post-per-post basis?
relative_link: false      # make links relative to the root folder?
future: false              # Display future posts?
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/threew/threew.github.io.git
  branch: gh-pages

search:
  path: search.xml
  field: post

sitemap:
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml

# Themes
## themes market: https://hexo.io/themes/
theme: next

# Generate categories from directory-tree
# Dependencies: https://github.com/xu-song/hexo-auto-category
# depth: the max_depth of directory-tree you want to generate, should > 0
auto_category:
 enable: true
 depth: 2
